
# Define the applications properties here:

TARGET = PocketSNES.out

SDKBIN := $(VRXSDK)\\bin
CC  := $(SDKBIN)\vrxcc
CXX := $(SDKBIN)\vrxcc
VRXHDR := $(SDKBIN)\vrxhdr
VLR := $(SDKBIN)\vlr
STRIP := 

ifdef V
	CMD:=
	SUM:=@\#
else
	CMD:=@
	SUM:=@echo
endif

INCLUDE = -Dndlib -Ipocketsnes -Isal/verix -Isal/ -Isal/verix/include -Isal/include -Ipocketsnes/include -Imenu -Ipocketsnes/verix -I pocketsnes/snes9x
CFLAGS =  -v -DVERIX -p -armcc,--c99 -DRC_OPTIMIZED -DNO_ASM -DNO_ROM_BROWSER $(INCLUDE)

CXXFLAGS = -v -DVERIX -p -DRC_OPTIMIZED -DNO_ASM -DNO_ROM_BROWSER $(INCLUDE)
LDFLAGS = $(CXXFLAGS) -g -p -map -symbols

# Find all source files
SOURCE = pocketsnes/snes9x menu sal/verix sal
SRC_CPP = $(foreach dir, $(SOURCE), $(wildcard $(dir)/*.cpp))
SRC_C   = $(foreach dir, $(SOURCE), $(wildcard $(dir)/*.c))
OBJ_CPP = $(patsubst %.cpp, %.o, $(SRC_CPP))
OBJ_C   = $(patsubst %.c, %.o, $(SRC_C))
OBJS    = $(OBJ_CPP) $(OBJ_C)


all: $(TARGET) pack

$(TARGET) : $(OBJS)
	$(SUM) "  LD      $@"
	$(CMD)$(CXX) $(CXXFLAGS) $^ $(LDFLAGS) -g $< -o $@

%.o: %.c
	$(SUM) "  CC      $@"
	$(CMD)$(CC) $(CFLAGS) -c $< -o $@

%.o: %.cpp
	$(SUM) "  CXX     $@"
	$(CMD)$(CXX) $(CXXFLAGS) -c $< -o $@

pack : 
	$(SUM) "  Pack     "
	$(CMD)$(VRXHDR) -s 2097152 -h 12582912 $(TARGET)

clean :
	$(SUM) "  CLEAN   ."
	$(CMD)rm -f $(OBJS) $(TARGET)
